version: '3.3'

services:
  monitoring_location_pygeoapi:
    build: .
    image: monitoring_location_pygeoapi
    ports:
      - "${PYGEOAPI_SERVER_PORT}:80"
    environment:
      - NWIS_DATABASE_ADDRESS=${NWIS_DATABASE_ADDRESS}
      - NWIS_DATABASE_PORT=${NWIS_DATABASE_PORT}
      - NWIS_DATABASE_NAME=${NWIS_DATABASE_NAME}
      - NWIS_SCHEMA_OWNER_USERNAME=${NWIS_SCHEMA_OWNER_USERNAME}
      - NWIS_SCHEMA_OWNER_PASSWORD=${NWIS_SCHEMA_OWNER_PASSWORD}
      - PYGEOAPI_SERVER_HOST=${PYGEOAPI_SERVER_HOST}
      - PYGEOAPI_SERVER_PORT=${PYGEOAPI_SERVER_PORT}
      - SCRIPT_NAME=$SCRIPT_NAME
      - PYGEOAPI_SERVER_URL=http://${PYGEOAPI_SERVER_HOST}:${PYGEOAPI_SERVER_PORT}${SCRIPT_NAME}
