version: '3.3'

services:
  monitoring_location_pygeoapi:
    build: .
    image: monitoring_location_pygeoapi
    ports:
      - "${PYGEOAPI_SERVER_PORT}:80"
    networks:
      geoapi:
        ipv4_address: ${PYGEOAPI_SERVER_IPV4}
    environment:
      - NWIS_DATABASE_HOST=${NWIS_DATABASE_HOST}
      - NWIS_DATABASE_PORT=${NWIS_DATABASE_PORT}
      - NWIS_DATABASE_USERNAME=${NWIS_DATABASE_USERNAME}
      - NWIS_DATABASE_PASSWORD=${NWIS_DATABASE_PASSWORD}
      - PYGEOAPI_SERVER_HOST=${PYGEOAPI_SERVER_HOST}
      - PYGEOAPI_SERVER_PORT=${PYGEOAPI_SERVER_PORT}
      - SCRIPT_NAME=$SCRIPT_NAME
      - PYGEOAPI_SERVER_URL=http://${PYGEOAPI_SERVER_HOST}:${PYGEOAPI_SERVER_PORT}${SCRIPT_NAME}

networks:
  geoapi:
    external:
      name: geoapi
