server:
  url: ${PYGEOAPI_SERVER_URL}
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  language: en-US
  cors: true
  pretty_print: true
  limit: 10
  # templates: /path/to/templates
  map:
    url: http://tile.stamen.com/terrain/{z}/{x}/{y}.jpg
    attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://www.openstreetmap.org/copyright">ODbL</a>.'
logging:
  level: DEBUG
  #logfile: /tmp/pygeoapi.log
metadata:
  identification:
    title: USGS NWIS Monitoring Locations
    description: OGC WFS3 API for geospatial information in NWIS
    keywords:
      - geospatial
      - usgs
      - api
    keywords_type: theme
    terms_of_service: None
    url: https://github.com/geopython/pygeoapi
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: U.S. Geological Survey
    url: https://www.usgs.gov/water
  contact:
    name: Jim Kreft
    position: Product Owner
    address: 8505 Research Way
    city: Middleton
    stateorprovince: WI
    postalcode: 53562
    country: USA
    #phone: 608-821-XXXX
    email: jkreft@usgs.gov
    #url: Contact URL
    #hours: Hours of Service
    #instructions: During hours of service.  Off on weekends.
    role: pointOfContact

datasets:
  monitoring-locations:
    title: NWIS Monitoring Locations
    description: USGS water monitoring locations managed in the National Water Information System
    keywords:
      - NWIS
    links:
      - type: text/html
        rel: canonical
        title: information
        href: https://waterdata.usgs.gov
        hreflang: en-US
    extents:
      spatial:
        bbox: [-180, -90, 180, 90]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS83
    provider:
      name: PostgreSQL
      data:
        host: ${NWIS_DATABASE_ADDRESS}
        dbname: ${NWIS_DATABASE_NAME}
        user: ${NWIS_SCHEMA_OWNER_USERNAME}
        password: ${NWIS_SCHEMA_OWNER_PASSWORD}
        port: ${NWIS_DATABASE_PORT}
        search_path:
          - ${NWIS_SCHEMA_NAME}
          - 'public'
      id_field: monitoring_location_id
      table: monitoring_location
      column_property_mapping: {
        'agency' : 'agency',
        'site_identification_number' : 'siteIdentificationNumber',
        'site_name' : 'siteName',
        'site_type' : 'siteType',
        'dms_latitude' : 'dmsLatitude',
        'dms_longitude' : 'dmsLongitude',
        'decimal_latitude' : 'decimalLatitude',
        'decimal_longitude' : 'decimalLongitude',
        'latitude_longitude_method' : 'latitudeLongitudeMethod',
        'latitude_longitude_accuracy' : 'latitudeLongitudeAccuracy',
        'latitude_longitude_accuracy_value' : 'latitudeLongitudeAccuracyValue',
        'latitude_longitude_accuracy_unit' : 'latitudeLongitudeAccuracyUnit',
        'latitude_longitude_datum' : 'latitudeLongitudeDatum',
        'decimal_latitude_longitude_datum' : 'decimalLatitudeLongitudeDatum',
        'district' : 'district',
        'state' : 'state',
        'county' : 'county',
        'country' : 'country',
        'land_net_location_description' : 'landNetLocationDescription',
        'name_of_location_map' : 'nameOfLocationMap',
        'scale_of_location_map' : 'scaleOfLocationMap',
        'altitude_of_guage_land_surface' : 'altitudeOfGuageLandSurface',
        'method_altitude_determined' : 'methodAltitudeDetermined',
        'altitude_accuracy' : 'altitudeAccuracy',
        'altitude_datum' : 'altitudeDatum',
        'subbasin_hydrologic_unit' : 'subbasinHydrologicUnit',
        'drainage_basin' : 'drainageBasin',
        'topographic_setting' : 'topographicSetting',
        'flags_for_instruments_at_site' : 'flagsForInstrumentsAtSite',
        'date_of_first_construction' : 'dateOfFirstConstruction',
        'date_site_established_or_inventoried' : 'dateSiteEstablishedOrInventoried',
        'drainage_area' : 'drainageArea',
        'contributing_drainage_area' : 'contributingDrainageArea',
        'time_zone_abbreviation' : 'timeZoneAbbreviation',
        'site_honors_daylight_savings_time' : 'siteHonorsDaylightSavingsTime',
        'data_reliability' : 'dataReliability',
        'data_other_gw_files' : 'dataOtherGwFiles',
        'national_aquifer' : 'nationalAquifer',
        'local_aquifer' : 'localAquifer',
        'local_aquifer_type' : 'localAquiferType',
        'well_depth' : 'wellDepth',
        'hole_depth' : 'holeDepth',
        'source_of_hole_depth' : 'sourceOfHoleDepth',
        'project_numer' : 'projectNumer',
        'site_id' : 'siteId',
        'agency_cd' : 'agencyCd',
        'site_tp_cd' : 'siteTpCd',
        'coord_meth_cd' : 'coordMethCd',
        'coord_acy_cd' : 'coordAcyCd',
        'coord_datum_cd' : 'coordDatumCd',
        'dec_coord_datum_cd' : 'decCoordDatumCd',
        'district_cd' : 'districtCd',
        'state_cd' : 'stateCd',
        'county_cd' : 'countyCd',
        'country_cd' : 'countryCd',
        'alt_meth_cd' : 'altMethCd',
        'alt_datum_cd' : 'altDatumCd',
        'huc_cd' : 'hucCd',
        'basin_cd' : 'basinCd',
        'topo_cd' : 'topoCd',
        'tz_cd' : 'tzCd',
        'local_time_fg' : 'localTimeFg',
        'reliability_cd' : 'reliabilityCd',
        'gw_file_cd' : 'gwFileCd',
        'nat_aqfr_cd' : 'natAqfrCd',
        'aqfr_cd' : 'aqfrCd',
        'aqfr_type_cd' : 'aqfrTypeCd',
        'depth_src_cd' : 'depthSrcCd',
        'calculated_huc_12' : 'calculatedHuc_12',
        'nwis_host' : 'nwisHost',
        'db_no' : 'dbNo',
        'site_web_cd' : 'siteWebCd',
        'monitoring_location_identifier' : 'monitoringLocationIdentifier'
      }
