server:
  url: ${PYGEOAPI_SERVER_URL}
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  language: en-US
  cors: true
  pretty_print: true
  limit: 10
  # templates: /path/to/templates
  map:
    url: http://tile.stamen.com/terrain/{z}/{x}/{y}.jpg
    attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://www.openstreetmap.org/copyright">ODbL</a>.'
logging:
  level: DEBUG
  #logfile: /tmp/pygeoapi.log
metadata:
  identification:
    title: USGS NWIS Monitoring Locations
    description: OGC WFS3 API for geospatial information in NWIS
    keywords:
      - geospatial
      - usgs
      - api
    keywords_type: theme
    terms_of_service: None
    url: https://github.com/geopython/pygeoapi
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: U.S. Geological Survey
    url: https://www.usgs.gov/water
  contact:
    name: Jim Kreft
    position: Product Owner
    address: 8505 Research Way
    city: Middleton
    stateorprovince: WI
    postalcode: 53562
    country: USA
    #phone: 608-821-XXXX
    email: jkreft@usgs.gov
    #url: Contact URL
    #hours: Hours of Service
    #instructions: During hours of service.  Off on weekends.
    role: pointOfContact

datasets:
  monitoring-locations:
    title: NWIS Monitoring Locations
    description: USGS water monitoring locations managed in the National Water Information System
    keywords:
      - NWIS
    links:
      - type: text/html
        rel: canonical
        title: information
        href: https://waterdata.usgs.gov
        hreflang: en-US
    extents:
      spatial:
        bbox: [-180, -90, 180, 90]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS83
    provider:
      name: PostgreSQL
      data:
        host: ${NWIS_DATABASE_ADDRESS}
        dbname: ${NWIS_DATABASE_NAME}
        user: ${NWIS_SCHEMA_OWNER_USERNAME}
        password: ${NWIS_SCHEMA_OWNER_PASSWORD}
        port: ${NWIS_DATABASE_PORT}
        search_path:
          - ${NWIS_SCHEMA_NAME}
          - 'public'
      id_field: monitoring_location_id
      table: "(select monitoring_location_id, geom,
               agency, site_identification_number, site_name, site_type,
               district, state, county, country,
               altitude_of_guage_land_surface, method_altitude_determined,
               altitude_accuracy, altitude_datum, national_aquifer, local_aquifer,
               local_aquifer_type, well_depth, hole_depth, source_of_hole_depth,
               agency_cd, district_cd,
               country_cd || ':' || state_cd as state_fips,
               country_cd || ':' || state_cd || ':' || county_cd as county_fips,
               country_cd as country_fips,
               subbasin_hydrologic_unit,
               'https://waterdata.usgs.gov/monitoring-location/' || site_identification_number as monitoring_location_url
               from monitoring_location) as monitoring_location"
      column_property_mapping: {
        'agency' : 'agency',
        'site_identification_number' : 'monitoringLocationNumber',
        'site_name' : 'monitoringLocationName',
        'site_type' : 'monitoringLocationType',
        'district' : 'district',
        'state' : 'state',
        'county' : 'county',
        'country' : 'country',
        'altitude_of_guage_land_surface' : 'monitoringLocationAltitudeLandSurface',
        'method_altitude_determined' : 'altitudeMethod',
        'altitude_accuracy' : 'altitudeAccuracy',
        'altitude_datum' : 'altitudeDatum',
        'national_aquifer' : 'nationalAquifer',
        'local_aquifer' : 'localAquifer',
        'local_aquifer_type' : 'localAquiferType',
        'well_depth' : 'wellDepth',
        'hole_depth' : 'holeDepth',
        'source_of_hole_depth' : 'holeDepthSource',
        'agency_cd' : 'agencyCode',
        'district_cd' : 'districtCode',
        'state_fips' : 'stateFIPS',
        'county_fips' : 'countyFIPS',
        'country_fips' : 'countryFIPS',
        'subbasin_hydrologic_unit' : 'hydrologicUnit',
        'monitoring_location_url' : 'monitoringLocationUrl'
      }
