projectName: iow-allegemein
dockerImageName: monitoring_location_pygeoapi-docker
memory: 2048
applicationName: monitoring_location_pygeoapi
rulePriority: 93
containerPort: 8080
healthCheck: /api/ogcAPI/collections
contextPath: /api/ogcAPI/*
gitRepoUrl: https://github.com/ACWI-SSWD/monitoring_location_pygeoapi.git
gitRepoCredentialsId: GITHUB_ACCESS_TOKEN
# configuration repository paths
configRepoPath: "wma/docker/monitoring_location_pygeoapi"
configCredentialsId: "wma-eto-eb-rsa"
