artifactoryPath: "wdfn"
gitlabPath: "wma/docker/monitoring_location_pygeoapi"
dockerImageName: "monitoring_location_pygeoapi"
repoPath: "ACWI-SSWD/monitoring_location_pygeoapi.git"
gitRepoUrl: https://github.com/ACWI-SSWD/monitoring_location_pygeoapi.git
gitRepoCredentialsId: "Jenkins-GitHub-Read-Write-Token"
deployJobName: "monitoring-location-pygeoapi-deploy"
projectName: iow-allegemein
memory: 2048
applicationName: monitoring-location-pygeoapi
rulePriority: 93
containerPort: 80
healthCheck: /api/ogcAPI/collections
contextPath: /api/ogcAPI/*
gitRepoCredentialsId: GITHUB_ACCESS_TOKEN
# configuration repository paths
configRepoPath: "wma/docker/monitoring_location_pygeoapi"
configCredentialsId: "wma-eto-eb-rsa"
